### ISSUE TITLE
Tab和PageView联动的时候，好像不能同步

### ISSUE THREAD

**Issue by ppxb** [kukyxs/flutter_arts_demos_app#1]
顶部tabs在第一个tab选择第三个tab，下方的pageview并不能按预期切换到对应的页面。第三个亦然。有解决办法吗？

**Comment by kukyxs** [comment]
可以使用 IndexStack 替换 PageView，再进行互相绑定

**Comment by ppxb** [comment]
> 可以使用 IndexStack 替换 PageView，再进行互相绑定

好的感谢，我一会儿试试。有联系方式吗？有些问题想咨询下你

**Comment by kukyxs** [comment]
加 wx 吧：yu_kuky
